### PR TITLE
Release v2.0.1

### PR DESCRIPTION
**Pull request by ericawright**
Status: **Ready for Review** 
Owner: @ericawright
Reviewers: @johnboxall @fractaltheory @MikeKlemarewski @mikenikles @stewartyu 

Version 2.0.1 release
## Issues Fixed

https://github.com/mobify/pikabu/issues/66
https://github.com/mobify/pikabu/issues/65
https://github.com/mobify/pikabu/issues/60
https://github.com/mobify/pikabu/issues/51
https://github.com/mobify/pikabu/issues/49

### CODE REVIEW

**Comment by kpeatt** [comment]
Excited that this is still actively developed! Nice work @ericawright.

**Comment by jansepar** [comment]
@ericawright do we want to get the changes to bower into this release?

**Comment by ericawright** [comment]
@jansepar it seems like it, at least that was what was suggested

**Comment by mikenikles** [comment]
I suggested to include the bower changes since this release is already a major upgrade to what's currently public.

**Comment by marlowpayne** [comment]
Maybe this is a bit too "blue-sky" for our current resourcing/workload, but it would be cool to see this release of Pikabu bring it up to current best practices like:
- [ ] Purge `lib/zeptojs` from the repo
- [ ] Prepare Pikabu for publishing on NPM
- [ ] Update JS linting to eslint and rulesets from code-style v2.4.2
- [ ] Update SCSS compilation to libsass through `grunt-sass`
- [ ] Lint SCSS with sass-lint

I'm happy to answer any questions about these best practices and how to make them happen.

**Comment by stewartyu** [comment]
@marlowpayne I agree these are great things to happen eventually, but the scope of this release should be to "release a working Pikabu 2.0" as the original Pikabu 2.0 release was broken. My recommendation would be to publish this release (unless there are functional blockers), and work on your items in 2.0.2.

**Pull request closed without merging**
